feat: add endpoint for donors data
einsteinfloripa/bucica-api pull request #122
Opened 2023-07-19 23:22 UTC by maecco

2023-07-20 14:40 UTC, vianaz requested changes

2023-07-20 14:40 UTC, vianaz commented on alembic/versions/762874570ad0_donors_table.py
> +    sa.Column('indiacacao', sa.String(), nullable=False),
```suggestion
    sa.Column('indicacao', sa.String(), nullable=False),
```

2023-07-20 14:40 UTC, vianaz commented on src/routers/donor_router.py
> +    print("Called")
por que esse print? se foi resquício de debug, poderia remover?

2023-07-20 14:40 UTC, vianaz commented on src/schemas/donor_schema.py
> +    indication: str = Field(..., min_length=3, alias="indicacao")
por que tem que ter um tamanho minimo de 3? poderia me explicar a regra de negocio por de tras disso?

2023-07-20 14:40 UTC, vianaz commented on tests/integration_tests/donors/test_donors.py
> +        print(response)
remover print

2023-07-20 14:40 UTC, vianaz commented on tests/integration_tests/donors/test_donors.py
> +@pytest.mark.t
remove mark desnecessario

2023-07-20 17:12 UTC, maecco commented on tests/integration_tests/donors/test_donors.py
> +@pytest.mark.t
@vianaz Feito!

2023-07-20 17:12 UTC, maecco commented on tests/integration_tests/donors/test_donors.py
> +        print(response)
@vianaz Feito!

2023-07-20 17:12 UTC, maecco commented on src/routers/donor_router.py
> +    print("Called")
@vianaz Feito!

2023-07-20 17:20 UTC, maecco commented on src/schemas/donor_schema.py
> +    indication: str = Field(..., min_length=3, alias="indicacao")
@vianaz na verdade eu fiz de forma arbitrária, na minha visão uma string com menos de 3 chars para um nome tem grande  chance de ser uma request feira por engano.

2023-07-21 17:26 UTC, vianaz commented on src/schemas/donor_schema.py
> +    indication: str = Field(..., min_length=3, alias="indicacao")
Imaginei, mas quero te trazer a reflexão que isso pode ser perigoso, consigo agora te dar um nome comum com 2 letras, `Lu`, então quer dizer que essa pessoa vai ser barrada de se cadastrar? Sei que Lu é um apelido, mas hoje temos muitas pessoas que preferem se cadastrar com seu `nome social`, então assim, não estou dizendo que tem certo e errado hahaha, isso pode ser uma característica da nossa API, no problem, mas quero trazer a reflexão:

- Vale a pena a gente barrar esse cadastro?
- É mais custoso para gente resolver esse problema de forma "pre" ou de forma "pos" cadastro? (Lembrando que iremos fazer consultas para gerar dados)

Pensando nesses pontos e se você tiver seguro que beleza, é isso só dale!

2023-07-21 18:11 UTC, maecco commented on src/schemas/donor_schema.py
> +    indication: str = Field(..., min_length=3, alias="indicacao")
Entendo, acho que você tem um ponto ai, como no nosso caso o nome não é algo critico e não requer precisão pode ser que o pessoal coloque apelidos mesmo.
Pensando também no proposito do limite, que era evitar cadastros errados, podem ter soluções melhores como dar a oportunidade do usuário de conferir o que foi escrito.

Quanto ao custo de resolver, acho que "pre" é quase sempre menos custoso.

Decidi tirar a limitação, aviso quando estiver feito.

2023-07-21 18:19 UTC, maecco commented on src/schemas/donor_schema.py
> +    indication: str = Field(..., min_length=3, alias="indicacao")
@vianaz Feito!

2023-07-22 14:00 UTC, vianaz approved these changes

2023-07-22 14:00 UTC, merged