Add sheet automation
einsteinfloripa/bucica-api pull request #164
Opened 2023-11-06 20:43 UTC by maecco

## Descrição

### Features:
- Faz o update automático para uma planilha do google sheets das presenças coletadas no dia.

2023-11-06 22:19 UTC, vianaz requested changes
@maecco não me ficou claro como posso testar essa PR, pode me dar um exemplo?

2023-11-06 22:19 UTC, vianaz commented on src/database/session.py
> -load_dotenv()
@maecco por que foi removido o `dotenv`?

2023-11-06 22:19 UTC, vianaz commented on src/database/sheet.py
> +        return f'{self.student_id} {self.first_half} {self.absence} {self.late} {self.created_at}'
@maecco pode ser usado `dataclasses`, o que acha? Assim remove a necessidade `__init__` e `__repr__`

2023-11-06 22:19 UTC, vianaz commented on src/database/sheet.py
> +        self.sheet_id = _sheet_id
@maecco geralmente usamos o `_<atributo_da_classe>` para metódos privados, então não faz muito sentido definir ele em um `constructor`, o mesmo para `attendance_buffer`, se ele não vai ser criado via  `constructor` melhor usar ele como privado, caso não queria expor essa propriedade, claro...

2023-11-06 22:35 UTC, maecco commented on src/database/session.py
> -load_dotenv()
@vianaz Esta funcionando apenas com o `os.getenv`.

2023-11-06 22:36 UTC, maecco commented on src/database/sheet.py
> +        return f'{self.student_id} {self.first_half} {self.absence} {self.late} {self.created_at}'
@vianaz Faz sentido sim, vou alterar!

2023-11-06 22:42 UTC, maecco commented on src/database/sheet.py
> +        self.sheet_id = _sheet_id
@vianaz Humm, sim. Acho que da pra eliminar o construtor mesmo. O attendance_buffer pode virar atributo de classe também né, já so uma instancia da classe é necessária.

2023-11-06 22:46 UTC, maecco commented
@vianaz Poisé, os testes fazem falta, eu vou escrever eles. No momento eu estou esperando o código em staging rodar na maquina do einstein para ver se as presenças são atualizadas.

2023-11-06 23:58 UTC, maecco commented on src/database/sheet.py
> +        self.sheet_id = _sheet_id
@vianaz Faz sentido do jeito que ficou agr?

2023-11-06 23:58 UTC, maecco commented on src/database/sheet.py
> +        return f'{self.student_id} {self.first_half} {self.absence} {self.late} {self.created_at}'
@vianaz feito!

2023-11-07 14:01 UTC, vianaz commented
@maecco beleza, fico no aguardo dos testes, assim que feito reviso e se tiver tudo certo aprovo :))

2023-11-08 19:01 UTC, maecco commented on tests/integration_tests/scripts/test_scripts.py
> +from src.models.students_model import Presenca
Essa solução foi equivocada pois a classe `MockerFixture` so será usada em commits posteriores. O que deveria ser feito era a remoção do parâmetro `mocker` das declarações das funções feitas no commit: 5d278022baab27bd13e26d1336463f1a048de29b

2023-11-27 08:16 UTC, vianaz approved these changes
Aparentemente está funcionando corretamente, como pode ser visto

![image](https://github.com/einsteinfloripa/bucica-api/assets/97882083/7e88afa7-9465-44bd-85e4-f78e53c2a263)

2023-11-29 14:33 UTC, merged