fix: change NotOngoinClass message from hardcoded to variable
einsteinfloripa/bucica-api pull request #87
Opened 2023-05-08 19:34 UTC by maecco

#Descriçao
Essa PR faz com que a mensagem de erro de aula não ocorrendo imprima os valores das variáveis responsáveis pelo inicio e final de cada aula.

2023-05-08 20:54 UTC, vianaz requested changes

2023-05-08 20:54 UTC, vianaz commented on src/services/students_service.py
> +                + f" e {self.second_half_begin} até {self.second_half_end}"
```suggestion
                f"Não há aula em andamento. As presenças só podem ser registradas
                  nos intervalo entre {self.first_half_begin} até {self.first_half_end} 
                  e {self.second_half_begin} até {self.second_half_end}"
```

Acho melhor fazer desse jeito do que ficar concatenando varias strings

2023-05-08 20:54 UTC, vianaz commented on src/services/students_service.py
> +    second_half_end = SecondClassHalf.END.value.strftime("%H:%M")
@maecco acredito que isso não é responsabilidade do `StudentService` fazer isso, talvez você pode mover isso pro `Schedule` ou pra um método na classe `Schedule` mais genérica, tipo `datatime_to_string` (pode ser um nome melhor) e essa método recebe como parâmetro a data e retorna ela formatada, deixando assim mais genérico

2023-05-08 22:03 UTC, maecco commented on src/services/students_service.py
> +    second_half_end = SecondClassHalf.END.value.strftime("%H:%M")
@vianaz humm, é verdade. Feito!

2023-05-08 22:04 UTC, maecco commented on src/services/students_service.py
> +                + f" e {self.second_half_begin} até {self.second_half_end}"
@vianaz Eu fiz isso porque facilita a leitura, sem concatenar fica uma string bastante longa. Fiz a mudança!

2023-05-09 09:02 UTC, vianaz commented on src/services/students_service.py
> +                + f" e {self.second_half_begin} até {self.second_half_end}"
@maecco se eu não me engano cê pode usar \, para fazer uma quebra linha no código mas que não afeta output, mas enfim, apenas comentando mesmo, vou resolver a thread :))

2023-05-09 09:06 UTC, merged